### ISSUE TITLE
Automatischer Daten Import von geocaching.com

### ISSUE THREAD

**Issue by andreaspeters** [andreaspeters/opencache-manager#1]
Es wäre schön, wenn man Caches von der geocaching Homepage automatisch importieren könnte, ohne über den Umweg einer GPX Datei und/oder einer dritt Software zu gehen.

**Comment by ChsRmb** [comment]
Wird jetzt wieder aktiv am Projekt gearbeitet? :)

**Comment by andreaspeters** [comment]
Ich Bugfixe aktuell nur. :-) Und dann schauen wir mal ob es mehr als drei Leute gibt die Interesse an OCM haben, damit es sich fuer mich lohnt weitere Features zu programmieren.

**Comment by ChsRmb** [comment]
Wäre auf jedenfall schön zusehen, dass das Projekt nicht stirbt :)

Aktuell gibts ja keine Alternative für Linux....

**Comment by andreaspeters** [comment]
crate a kanban task for that
