### ISSUE TITLE
OCM auf Debian 10 Buster (testing)

### ISSUE THREAD

**Issue by r-krelaus** [andreaspeters/opencache-manager#12]
Hallo Andreas,

lange Zeit hat OCM treu seine Dienste geleistet, doch jetzt kriege ich es einfach nicht zum Laufen. Gestern habe ich Debian neu installiert (testing), um danach OCM zu compilieren, was auch ohne Fehlermeldungen geklappt hat.
Wenn ich aber OCM im Terminal starte, bekomme ich eine Reihe von Fehlermeldungen, die ich aber nicht deuten kann:

`(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,
(ocm-gtk:11315): Gtk-WARNING **: Im Modulpfad »smooth« konnte keine Themen-Engine gefunden werden,

(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_child_set_property: assertion 'GTK_IS_WIDGET (child)' failed
(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_child_set_property: assertion 'GTK_IS_WIDGET (child)' failed
(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
(ocm-gtk:11315): Gtk-CRITICAL **: IA__gtk_container_child_set_property: assertion 'GTK_IS_WIDGET (child)' failed

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at ocmgtk.OCMMainWindow..ctor (ocmgtk.OCMApp app) [0x00022] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.InitializeApp (System.String filename, System.Boolean quitAfterImport) [0x00087] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Start (System.String filename) [0x0003b] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Start () [0x00000] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Main (System.String[] args) [0x000da] in <31d1ed11914a4e95b3170d07c09311db>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at ocmgtk.OCMMainWindow..ctor (ocmgtk.OCMApp app) [0x00022] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.InitializeApp (System.String filename, System.Boolean quitAfterImport) [0x00087] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Start (System.String filename) [0x0003b] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Start () [0x00000] in <31d1ed11914a4e95b3170d07c09311db>:0 
  at ocmgtk.OCMApp.Main (System.String[] args) [0x000da] in <31d1ed11914a4e95b3170d07c09311db>:0 
`

Dier ersten GTK-Warnungen lassen sich umgehen, indem ich ein anderes Desktop-Thema wähle (ich arbeite mit xfce4). Der Rest bleibt.

Hast du vielleicht eine Idee, was dahinter stecken könnte? Das einzige, was mir spontan einfallen würde, wäre ein älteres Linux in einer VM für OCM zu benutzen.

Grüße
Ralf

**Comment by andreaspeters** [comment]
Moin Ralf,

bitte versuche den 0.1.17 branch. Der funktioniert. :-)

VG
Andreas

**Comment by r-krelaus** [comment]
Hallo Andreas,
leider habe ich das Problem nicht in den Griff bekommen. Irgendwie vermute ich, dass noch irgendein Paket installiert werden muss, aber welches?
Beim Compilieren schien ja alles wichtige an Libraries da gewesen zu sein. Gibt es eine Liste von Paketen, die unter Debian mindestens installiert sein müssen?

Grüße
Ralf

**Comment by andreaspeters** [comment]
Magst Du mir bitte alle Befehle aufschreiben die Du benutzt? 😃 Aber bitte nur die Befehle, nicht die Ausgaben. 😃
