### ISSUE TITLE
Broken matrix federation

### ISSUE THREAD

**Issue by ChsRmb** [andreaspeters/opencache-manager#13]
Hey,
I've tried to join your matrix chat from another instance, but I can't join them. 
After a quick troubleshooting, I found a broken matrix federation... :(

Cheers,
ChaosRambo

**Comment by andreaspeters** [comment]
Thats correct, we disabled the federation because of extrem load on our server. 😖

**Comment by andreaspeters** [comment]
So... I give the matrix server more ressource. Will see how the enabled federation will be.
