### ISSUE TITLE
"Unable to load page" - keine Kartenansicht

### ISSUE THREAD

**Issue by J-U-B** [andreaspeters/opencache-manager#14]
Hallo Andreas,

beim Start von OCM lacht mich nun eine Fehlermeldung an:

> **Unable to load page**
> Problem occurred while loading the URL http://andreas-peters.net/ocm/web/wpt_viewer.html?
> Cannot connect to destination (andreas-peters.net)

Der Server antwortet derzeit in der Tat nicht.
Es gibt leider keinen Fallback, wenn wpt_viewer.html nicht erreichbar ist.

Viele Grüsse, Jens

**Comment by J-U-B** [comment]
Hallo Andreas,

meinem Branch [wpt_viewer_fallback](https://github.com/J-U-B/opencache-manager/tree/wpt_viewer_fallback) hab ich (temporär) komplett auf lokale Files umgestellt.
Das betrifft wpt_viewer.html, OpenLayers.js und OpenStreetMap.js.
Da das erst mal nur ein Workaround ist, hab ich keinen Pull-Request erstellt.

Welchen Hintergrund hatte der Download der wpt_viewer.html nochmal? Lag das am API-Key für Google Maps?
Vielleicht könnte man dann zumindest ein lokales File benutzen, wenn Dein Server mal nicht erreichbar ist. Ansonsten gibt es im OCM gar keine Karten.

----

Beim Start bleibt die Kartenansicht bei mir allerdings weiterhin zunächst leer. Erst wenn ich auf _OSM: Mapnik_ oder _Google Satellite_ umstellen bekomme ich eine Karte zu sehen. Anschliessend funktioniert auch _Google Street Map_. - Aber das ist ein anderer Bug.

Es gab noch einen kleinen Fehler in Translations/Makefile in: <code>make disclean</code> löscht dort auch _Makefile.in_ und die _*.po_-Files. 

VG, Jens

**Comment by andreaspeters** [comment]
Hallo Jens,

Frohes neues. 😃

Ich hatte Server Umstellungen am Wochenende, daher war alles offline.
Eine ocmmap offline Version präferiere ich in der Tat. Am besten eine die auch ohne online osm auskommt. Die Kartendaten hierzu sind aber viele GB gross.

Das benutzen der Lokalen Daten hatte bei mir nicht funktioniert. Ich werde nachher mal einen Branch erstellen, auf dem wir Deine Änderungen pulln können. Wenn dann alles bei mir funktioniert kommt die Änderung in den Master. Was denkst Du?

VG
Andreas

**Comment by J-U-B** [comment]
Hallo Andreas,

auch Dir alles Gute für's neue Jahr.

Da der Server irgendwann immerhin eine nginx-Seite gezeigt hat, hab ich mir schon gedacht, dass du daran arbeitest. Dem OCM half das natürlich erst mal nicht.

Eine Offline-Version der OSM-Karten würde ich auch begrüssen. Nur muss ich zugeben, dass mir dazu (bisher) das KnowHow fehlt das selber umzusetzen. Die Datenmenge für die Karten sehe ich aber unkritisch; die muss ja niemand benutzen. Lokal geht es dann doch schneller als über eine lahme Leitung.

Zuerst wollten die lokalen Daten bei mir auch nicht funktionieren. Doch das lag an meinen unglücklich konstruierten URI. Jetzt geht die ganze Sache doch schon merklich flotter, nachdem sich die OpenLayers.js nicht mehr durch die Leitung quälen muss. (Meine DSL-Leitung ist eine Katastrophe!)

In meinem Branch (von 0.1.17) hab ich <code>Makefile.in</code> schon entsprechend angepasst, damit die Files auch alle korrekt installiert werden. Das distclean-Problem für die Translations ist da auch schon behoben.
Wenn Du mit den Änderungen einverstanden bist, können die natürlich gerne in den Master wandern.

Viele Grüsse,
Jens

**Comment by andreaspeters** [comment]
:-) Dann erstell doch mal bitte einen pull request.

**Comment by andreaspeters** [comment]
achso, gegen branch "osm"

**Comment by J-U-B** [comment]
Ich hab nun die Base für den Pull request korrigiert.

**Comment by andreaspeters** [comment]
So... Musste erstmal webkit sharp neucompilieren. Hat viele Stunden gedauert. :-( Dein Pull funktioniert jedenfalls. Ich sehe aber nicht das Du Dich unter den Mitwirkenden eingetragen hast. :-(

**Comment by J-U-B** [comment]
Hallo Andreas,

doch, ich stehe etwas dezent im [OCMMainWindow.cs](https://github.com/andreaspeters/opencache-manager/blob/osm/ocm-gtk/Application/OCMMainWindow.cs) in Zeile 1219 bei den Credits. Soo viel habe ich ja bislang noch nicht beigesteuert. ;-)

Vor einigen Tagen hatte ich noch etwas mit den (fast) lokalen Maps experimentiert.
Ideal wäre wohl etwas, das z.B. die Karten vom Garmin benutzen kann. Doch da sehe ich zumindest derzeit kein Land.
Auf dem ersten Blick hab ich Hoffnung auf OsmSharp gesetzt, aber das kann die Karten leider nicht selbst rendern. Mir ist noch keine Bibliothek begegnet, die das OCM intern erledigen könnte. Davon abgesehen muss das ja auch mit dem bestehenden Konzept verheiratet werden.
Also bliebe nur eine lokale Mapnik-Instanz (oder ein anderer Renderer) oder ein Cache-Proxy. Ich hab erst mal ein wenig mit [TileStache](https://github.com/TileStache/TileStache) experimentiert und über ein entsprechendes [XML-File](https://gist.github.com/J-U-B/55965b87f6d52287bed648bf9d8e7e34) eingebunden.

VG, Jens

**Comment by andreaspeters** [comment]
Wenn Du magst trage ich dich unter den mitwirkenden ein. 😃

Tiled mapping wäre richtig Klasse,  ist aber schäuslich zu programmieren.

**Comment by andreaspeters** [comment]
erstelle doch mal bitte unter wekan.aventer.biz einen account. dann gebe ich dir rechte auf das ocm kanban board.

**Comment by andreaspeters** [comment]
ich habe mich uebrigens geirrt, es funktioniert bei mir doch nicht. das osm fenster bleibt immer leer. :-( stattdessen bekomme ich folgende fehlemeldung in der console.

```
➜  Release_Translated git:(osm) ✗ mono ocm-gtk.exe                 
/usr/local/share/locale
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
myPosition = [lat=NOPE&lon=NIXDA]
localSite = [file:///home/andreas/Projekte/opencache-manager/ocm-gtk/bin/Release_Translated/web/]
** Message: console message: undefined @1: ReferenceError: Can't find variable: clearActiveMarkers

** Message: console message: undefined @1: ReferenceError: Can't find variable: clearExtraMarkers

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @1: ReferenceError: Can't find variable: addMapRenderer

** Message: console message: undefined @0: TypeError: undefined is not a function
```

**Comment by J-U-B** [comment]
* So, ich hab's endlich geschafft den Wekan-Account einzurichten.
* Ich hab auch nichts dagegen bei den Mitwirkenden zu stehen. ;-)
* Hab eben nochmal deinen osm-Merge ausgecheckt und getestet. Hier funktioniert es. Ich werde es aber noch auf einem anderen System ausprobieren.

**Comment by J-U-B** [comment]
Build-Tests und Check mit lokalen Files:
- Ubuntu 14.04 LTS: O.K.
- Ubuntu 16.04 LTS: O.K.
- Windows 7: Build nicht erfolgreich
- Fedora/Centos: ausstehend

Zumindest unter Ubuntu konnte ich den obigen Fehler bisher nicht nachvollziehen. Unter welchem Linux kommt es zu dem Fehler?
Was hat der OCM eigentlich mit Java zu tun?

**Comment by andreaspeters** [comment]
Ich verwende arch linux mit dem aktuellsten mono (Stable 5.0.0.100/9667aa6). Was OCM mit Java zu tun hat, war ebenfalls mein erster Gedanke als ich die Meldung gesehen habe. Und ich kann Dir keine Antwort darauf liefer ausser ein leises *hmpf*. 

In Wekan habe ich Dir übrigens die OSM Tasks zugewiesen. :-)

**Comment by J-U-B** [comment]
Weitere Tests:
* Ubuntu 18.04: O.K.
   * benötigt libcanberra-gtk-module
* Debian 9.3: O.K.
* Fedora 27: in Vorbereitung
* Arch Linux: in Vorbereitung

**Comment by J-U-B** [comment]
Bisherige Tests:
* Ubuntu 14.04 LTS: O.K.
* Ubuntu 16.04 LTS: O.K.
* Ubuntu 18.04: O.K.
   * benötigt libcanberra-gtk-module
* Debian 9.3 (Stretch): O.K.
* Debian 10 (Buster): O.K.
   * webkit-sharp nicht in Repository (https://tracker.debian.org/pkg/webkit-sharp)
   * libwebkit1.1-cil_0.3-7_all.deb und libwebkit-cil-dev_0.3-7_all.deb aus http://ftp.debian.org/debian/pool/main/w/webkit-sharp/
* SuSE Leap 42.3: O.K.
* Fedora 27: FAIL - Probleme bei Build mit webkit-sharp-devel
* Centos 7.4.1708: FAIL - Probleme bei Build mit dbus-sharp-2.0 (nur dbus-sharp-1.0 in Repositories)
* Arch Linux: O.K.
   * Build webkitgkt2 und webkitsharp via yaourt
   * Mono 5.0.0.100-2
   * Oracle JRE 9.0.4 wird zwar nicht benötigt, wurde dennoch installiert
   * Opencache-Manager-Branch osm (auch via yaourt) O.K.
-----

> WebKitGTK+ 2.4 is known to have many security vulnerabilities that will NOT be fixed.

...mittelfristig sollte zu <code>webkit2gtk</code> portiert werden. Fedora/Centos/RHEL liefern <code>webkitgtk</code> bereits nicht mehr.

**Comment by J-U-B** [comment]
Wieso wird bei Dir
> localSite = [file:///${OCM_PREFIX}/ocm-gtk/bin/Release_Translated/web/]

verwendet?
Hier heisst es immer:
> localSite = [file:///${OCM_PREFIX}/web/]

Apropos _translated_: Ich bekomme stets das englische Interface zu sehen.

**Comment by andreaspeters** [comment]
was hast du gemacht das ocm unter 18.04 funktioniert? :-) habe hier jemand im chat der hilfe benoetigt es dort zum laufen zu bringen. webkit1.1 gibt es dort ja nicht mehr.

**Comment by J-U-B** [comment]
Zuletzt getestet habe ich mit meinem Branch [wpt_viewer_fallback](https://github.com/J-U-B/opencache-manager/tree/wpt_viewer_fallback).
In meinem ausführlicheren Kommentar zu diesem Issue vom 24. Januar hatte ich die Problematik schon bei Debian 10 (Buster) beschrieben und <code>libwebkit1.1-cil_0.3-7_all.deb</code> und <code>libwebkit-cil-dev_0.3-7_all.deb</code> aus alternativen Quellen installiert (siehe oben).
Von Ubuntu 18.04 hatte ich seinerzeit eine pre Beta eingesetzt. Da waren beide Bibliotheken m.E. noch in der Distribution enthalten. Scheinbar sind sie in der Beta nun endgültig herausgeflogen und werden auch in der Release nicht mehr enthalten sein.

Die veralteten Bibliotheken aus anderen Quellen zu beziehen ist ein hässlicher (temporärer) Workaround. Da immer mehr Distributionen auf die veralteten und nicht mehr gepflegten Bibliotheken verzichten hilft nur noch eine Portierung zu <code>webkit2gtk</code>

**Comment by J-U-B** [comment]
Da die Patches aus [wpt_viewer_fallback](https://github.com/J-U-B/opencache-manager/tree/wpt_viewer_fallback) inzwischen in deinen [osm](https://github.com/andreaspeters/opencache-manager/tree/osm)-Branch eingeflossen sind, schlage ich vor dieses Ticket zu schliessen und für die webkit2gtk-Portierung ein anderes zu öffen.

**Comment by andreaspeters** [comment]
Gute Idee, ich schliesse mal. :-)
