### ISSUE TITLE
Kartenanzeige funktioniert nicht mehr

### ISSUE THREAD

**Issue by r-krelaus** [andreaspeters/opencache-manager#3]
Hallo,
heute musste ich überrascht feststellen, dass in OCM 1.0.16b keine Karte mehr angezeigt wird.
Meldung im Kartenbereich:
503 Service Unavailable
No server is available to handle this request.

Vielleicht hat der Kartenserver seine Adresse gewechselt?

Grüße
Ralf

**Comment by andreaspeters** [comment]
Ah... Danke für den Hinweis! Ich kümmer mich drum.

**Comment by andreaspeters** [comment]
So... Funktioniert wieder. Ein Update muss nicht eingespielt werden.

**Comment by r-krelaus** [comment]
Wunderbar. Vielen Dank. Was wäre ich ohne opencache-manager.
