### ISSUE TITLE
SHAMROCK_EXPAND_LIBDIR / @expanded_libdir@ - Ersetzung erfolgt nicht

### ISSUE THREAD

**Issue by J-U-B** [andreaspeters/opencache-manager#4]
Das `configure`-Script gibt u.a. die Meldung:
<pre>
./configure: line 2467: SHAMROCK_EXPAND_LIBDIR: command not found
./configure: line 2468: SHAMROCK_EXPAND_BINDIR: command not found
./configure: line 2469: SHAMROCK_EXPAND_DATADIR: command not found
</pre>

Die Variablen in `ocm-gtk` werden letztendlich nicht auf gelöst:
<pre>
#!/bin/sh
cd "@expanded_libdir@/opencachemanager"
exec mono "@expanded_libdir@/opencachemanager/ocm-gtk.exe" "$@"
</pre>

Das Problem besteht seit [commit d003b49](https://github.com/andreaspeters/opencache-manager/commit/d003b49c9a96ad59cfa0b4d2a4380d42e1fc7bce).

**Comment by andreaspeters** [comment]
Hi! 

Schaue ich mir an, vielen Dank. :-)

Andreas
