### ISSUE TITLE
Kartenanzeige funktioniert wieder nicht

### ISSUE THREAD

**Issue by r-krelaus** [andreaspeters/opencache-manager#6]
Hallo Andreas,

OCM ist mal wieder ohne Karte. Auf der Konsole kommen Fehlermeldungen folgender Art:

`** Message: console message: http://andreas-peters.net/ocm/web/wpt_viewer.html?lat=52.9858166666667&lon=10.0885333333333 @1: ReferenceError: Can't find variable: addMapRenderer`

Ist das ein Kartenserver, der bei dir läuft und uns die Karten liefert? Oder wie muss man sich das vorstellen? Gibt es nicht die Möglichkeit, die Karten direkt z.B. von OSM abzurufen? Oder kann ich mit einfachen Mitteln sowas lokal bei mir laufen lassen?

Grüße
Ralf

**Comment by andreaspeters** [comment]
Moin Ralf,

ein Kartenserver ist es nicht, sondern eher eine Webseite mit Kartenansicht. Ich hatte es 1zu1 vom Entwickler des OpenCacheManagers übernommen. In der Mono Lib gab es so viele Änderungen, so das die Karte nicht mehr funktionierte. :-( Aktuell sind wir daher auf die Verfügbarkeit meiner Homepage angewiesen.

Theoretisch kann jeder den Viewer bei sich hosten. Benötigt wird lediglich ein Webserver und halt das umstellen der URL im SourceCode. 

Viele Grüße,
Andreas

**Comment by andreaspeters** [comment]
Kartendarstellung funktioniert wieder.

**Comment by r-krelaus** [comment]
Hallo Andreas,

danke für das schnelle wiederherstellen der Kartenfunktion.
Ich überlege, ob ich das nicht lokal bei mir laufen lassen möchte. Würde das die Kartendarstellung nicht auch ein wenig beschleunigen? Und ein Webserver läuft sowieso im lokalen Netzwerk.

Noch eine Idee. Wir hatten ja schonmal darüber gesprochen, wie verbreitet die Nutzung von OCM überhaupt ist. Mit den Zugriffen auf die Kartenansicht auf deinem Server müsstest du doch die Nutzerzahl zumindest abschätzen können. Fände ich mal interessant.

Grüße
Ralf

**Comment by J-U-B** [comment]
Hallo Andreas,
Hallo Ralf,

lokale Karten habe ich eigentlich auch schon lange auf meiner Wunschliste. Allerdings habe ich dabei weniger an einen lokalen Map-(Web-)Server als an einen direkten Zugriff auf die IMG-Files gedacht.

Die regelmässige Server-Abfrage (und damit Nutzungsprotokollierung) ist mir ehrlich gesagt ein Dorn im Auge.

Viele Grüsse,
Jens

**Comment by andreaspeters** [comment]
Die OCM Karten Zugriffe tracke ich nicht mit. Dafür wäre es mir dem Nutzer der Software gegenüber zu intransparent. Nicht einmal mein WebServer loggt den Zugriff. Da bin ich eigen. :-) @Jens: Beruhigt? :-)

Da immer die gleichen  Personen Rückmeldung geben wenn etwas nicht funktioniert, gehe ich davon aus, dass kaum einer die Version verwendet welche von mir gepflegt wird. 

@Ralf: Die Kartendarstellung wird es nicht wirklich beschleunigen. Da die Bilder, wie Jens es sagt, ja von Deinem Browser eh aus dem Internet geladen werden. D.h. das einzige was Du einsparst, sind die 1.1M an HTML, JavaScript und CSS von meiner Homepage. 

@Jens: Lokale Karten wären definitiv super. :-) Allerdings sind das wirklich große Datenmengen. Deutschland in einer Karten Auflösung die Akzeptabel ist, hat eine Größe  von 700MB. Und hier eine Management zu programmieren wo man ggfs. auswählt welche Kartenabschnitte man herunterladen  möchte, ist etwas übertrieben. :-)

Viele Grüße,
Andreas

**Comment by andreaspeters** [comment]
Ich habe mal ein Chat Raum eingerichtet: https://chat.aventer.biz/#/room/#ocm:matrix.aventer.biz
