### ISSUE TITLE
make clean und distclean zu rabiat

### ISSUE THREAD

**Issue by dorski** [andreaspeters/opencache-manager#9]
Ich bin unter Debian (stretch) gerade über issue #2 gestolpert. Um den Trick mit dem Zurücksetzen der Versionsnummern auszuprobieren habe ich im ausgecheckten branch (master) `make distclean` gesagt – danach wird nicht mehr richtig gebaut: `config.status: error: cannot find input file: `Translations/Makefile.in'` Offenbar wird `Translations/Makefile.in` entweder ohne Not entsorgt oder es fehlt eine Regel zum (Neu)bauen der Datei.

**Comment by andreaspeters** [comment]
nach "make disclean" musst du ./configure erneut aufrufen. Dies erzeugt die entsprechende Makefile.in.
